### ISSUE TITLE
The first step, load_data_sql (sql-finetune-bot), failing on modal

### ISSUE THREAD

**Issue by rsrs30303** [run-llama/modal_finetune_sql#9]
Hi, I am trying this exercise. Created modal account and provisioned a token. 

The first step,  **_load_data_sql_** (**sql-finetune-bot** running on on **_modal_**),  failing after some time. Including log entries.  Hope someone can provide a resolution. Thanks in advance.

=== Log entries

/

main

Live Usage: $0.05

App Logs
[sql-finetune-bot](https://modal.com/<account>/apps/ap-gvzb0bbEyykRPrpGkotg8c)
Search logs (⌘K)
Filter by function
More settings
Filtering by

runner: ta-E4aA5ARd6oiGO5CBTaa0iD

input: in-64ucBr5rNEJf15ciiIsLnq
remove this filter if logs are missing
Load more
No logs for 1d
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 518, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 659, in run_input
    res = imp_fun.fun(*args, **kwargs)
  File "/root/src/load_data_sql.py", line 24, in load_data_sql
    dataset = load_dataset("b-mc2/sql-create-context")
  File "/opt/conda/lib/python3.9/site-packages/datasets/load.py", line 1759, in load_dataset
    builder_instance = load_dataset_builder(
  File "/opt/conda/lib/python3.9/site-packages/datasets/load.py", line 1496, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/opt/conda/lib/python3.9/site-packages/datasets/load.py", line 1218, in dataset_module_factory
    raise e1 from None
  File "/opt/conda/lib/python3.9/site-packages/datasets/load.py", line 1195, in dataset_module_factory
    return HubDatasetModuleFactoryWithoutScript(
  File "/opt/conda/lib/python3.9/site-packages/datasets/load.py", line 767, in get_module
    else get_data_patterns_in_dataset_repository(hfh_dataset_info, self.data_dir)
  File "/opt/conda/lib/python3.9/site-packages/datasets/data_files.py", line 675, in get_data_patterns_in_dataset_repository
    return _get_data_files_patterns(resolver)
  File "/opt/conda/lib/python3.9/site-packages/datasets/data_files.py", line 236, in _get_data_files_patterns
    data_files = pattern_resolver(pattern)
  File "/opt/conda/lib/python3.9/site-packages/datasets/data_files.py", line 486, in _resolve_single_pattern_in_dataset_repository
    glob_iter = [PurePath(filepath) for filepath in fs.glob(PurePath(pattern).as_posix()) if fs.isfile(filepath)]
  File "/opt/conda/lib/python3.9/site-packages/fsspec/spec.py", line 606, in glob
    pattern = glob_translate(path + ("/" if ends_with_sep else ""))
  File "/opt/conda/lib/python3.9/site-packages/fsspec/utils.py", line 734, in glob_translate
    raise ValueError(
ValueError: Invalid pattern: '**' can only be an entire path component
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 518, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 659, in run_input
    res = imp_fun.fun(*args, **kwargs)
  File "/root/src/load_data_sql.py", line 24, in load_data_sql
    dataset = load_dataset("b-mc2/sql-create-context")
  File "/opt/conda/lib/python3.9/site-packages/datasets/load.py", line 1759, in load_dataset
    builder_instance = load_dataset_builder(
  File "/opt/conda/lib/python3.9/site-packages/datasets/load.py", line 1496, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/opt/conda/lib/python3.9/site-packages/datasets/load.py", line 1218, in dataset_module_factory
    raise e1 from None
  File "/opt/conda/lib/python3.9/site-packages/datasets/load.py", line 1195, in dataset_module_factory
    return HubDatasetModuleFactoryWithoutScript(
  File "/opt/conda/lib/python3.9/site-packages/datasets/load.py", line 767, in get_module
    else get_data_patterns_in_dataset_repository(hfh_dataset_info, self.data_dir)
  File "/opt/conda/lib/python3.9/site-packages/datasets/data_files.py", line 675, in get_data_patterns_in_dataset_repository
    return _get_data_files_patterns(resolver)
  File "/opt/conda/lib/python3.9/site-packages/datasets/data_files.py", line 236, in _get_data_files_patterns
    data_files = pattern_resolver(pattern)
  File "/opt/conda/lib/python3.9/site-packages/datasets/data_files.py", line 486, in _resolve_single_pattern_in_dataset_repository
    glob_iter = [PurePath(filepath) for filepath in fs.glob(PurePath(pattern).as_posix()) if fs.isfile(filepath)]
  File "/opt/conda/lib/python3.9/site-packages/fsspec/spec.py", line 606, in glob
    pattern = glob_translate(path + ("/" if ends_with_sep else ""))
  File "/opt/conda/lib/python3.9/site-packages/fsspec/utils.py", line 734, in glob_translate
    raise ValueError(
ValueError: Invalid pattern: '**' can only be an entire path component
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 518, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 659, in run_input
    res = imp_fun.fun(*args, **kwargs)
  File "/root/src/load_data_sql.py", line 24, in load_data_sql
    dataset = load_dataset("b-mc2/sql-create-context")
  File "/opt/conda/lib/python3.9/site-packages/datasets/load.py", line 1759, in load_dataset
    builder_instance = load_dataset_builder(
  File "/opt/conda/lib/python3.9/site-packages/datasets/load.py", line 1496, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/opt/conda/lib/python3.9/site-packages/datasets/load.py", line 1218, in dataset_module_factory
    raise e1 from None
  File "/opt/conda/lib/python3.9/site-packages/datasets/load.py", line 1195, in dataset_module_factory
    return HubDatasetModuleFactoryWithoutScript(
  File "/opt/conda/lib/python3.9/site-packages/datasets/load.py", line 767, in get_module
    else get_data_patterns_in_dataset_repository(hfh_dataset_info, self.data_dir)
  File "/opt/conda/lib/python3.9/site-packages/datasets/data_files.py", line 675, in get_data_patterns_in_dataset_repository
    return _get_data_files_patterns(resolver)
  File "/opt/conda/lib/python3.9/site-packages/datasets/data_files.py", line 236, in _get_data_files_patterns
    data_files = pattern_resolver(pattern)
  File "/opt/conda/lib/python3.9/site-packages/datasets/data_files.py", line 486, in _resolve_single_pattern_in_dataset_repository
    glob_iter = [PurePath(filepath) for filepath in fs.glob(PurePath(pattern).as_posix()) if fs.isfile(filepath)]
  File "/opt/conda/lib/python3.9/site-packages/fsspec/spec.py", line 606, in glob
    pattern = glob_translate(path + ("/" if ends_with_sep else ""))
  File "/opt/conda/lib/python3.9/site-packages/fsspec/utils.py", line 734, in glob_translate
    raise ValueError(
ValueError: Invalid pattern: '**' can only be an entire path component
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 518, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 659, in run_input
    res = imp_fun.fun(*args, **kwargs)
  File "/root/src/load_data_sql.py", line 24, in load_data_sql
    dataset = load_dataset("b-mc2/sql-create-context")
  File "/opt/conda/lib/python3.9/site-packages/datasets/load.py", line 1759, in load_dataset
    builder_instance = load_dataset_builder(
  File "/opt/conda/lib/python3.9/site-packages/datasets/load.py", line 1496, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/opt/conda/lib/python3.9/site-packages/datasets/load.py", line 1218, in dataset_module_factory
    raise e1 from None
  File "/opt/conda/lib/python3.9/site-packages/datasets/load.py", line 1195, in dataset_module_factory
    return HubDatasetModuleFactoryWithoutScript(
  File "/opt/conda/lib/python3.9/site-packages/datasets/load.py", line 767, in get_module
    else get_data_patterns_in_dataset_repository(hfh_dataset_info, self.data_dir)
  File "/opt/conda/lib/python3.9/site-packages/datasets/data_files.py", line 675, in get_data_patterns_in_dataset_repository
    return _get_data_files_patterns(resolver)
  File "/opt/conda/lib/python3.9/site-packages/datasets/data_files.py", line 236, in _get_data_files_patterns
    data_files = pattern_resolver(pattern)
Expand
  File "/opt/conda/lib/python3.9/site-packages/datasets/data_files.py", line 486, in _resolve_single_pattern_in_dataset_repository
    glob_iter = [PurePath(filepath) for filepath in fs.glob(PurePath(pattern).as_posix()) if fs.isfile(filepath)]
  File "/opt/conda/lib/python3.9/site-packages/fsspec/spec.py", line 606, in glob
    pattern = glob_translate(path + ("/" if ends_with_sep else ""))
  File "/opt/conda/lib/python3.9/site-packages/fsspec/utils.py", line 734, in glob_translate
    raise ValueError(
ValueError: Invalid pattern: '**' can only be an entire path component

**Comment by rsrs30303** [comment]
I updated the **_datasets_**  following the resolution of issue#2 . That seems to address this as well.
